version: "3.1"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "${APP_HOST:-8000}:8000"
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: