version: "3.1"

services:
  nginx:
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    ports:
      - "8000:80"
    env_file:
      - ./frontend/.env
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: db
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15.2
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: