# Generated by Django 3.2.16 on 2023-02-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalinstance',
            name='object',
        ),
        migrations.AddField(
            model_name='instance',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
