# Generated by Django 3.2.16 on 2023-02-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230218_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='image',
        ),
    ]
