# Generated by Django 4.0.10 on 2023-05-31 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_alter_contractnumber_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Место нахождения', 'verbose_name_plural': 'Помещения'},
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.instance')),
                ('report', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
