# Generated by Django 4.0.10 on 2023-05-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('finish', 'Завершено'), ('in_progress', 'В процессе')], default='in_progress', max_length=16),
        ),
    ]
