# Generated by Django 4.0.10 on 2023-05-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_report_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='finished_at',
        ),
    ]
